language: node_js
node_js:
  - "10"

cache:
  npm: true

services:
  - docker

before_install:
  - npm install -g prisma
  - npm install
  - docker-compose -f prisma/docker-compose.yml up -d

stages:
  - test
  - build
  - deploy

jobs:
  include:
    - stage: test
      script:
        - echo "Run Prisma Deployment"
        - cd prisma && prisma generate && prisma deploy
        - echo "Start installation and test"
        - npm run test
    - stage: build
      script:
        - cd prisma && prisma generate && prisma deploy
        - npm run build

    - stage: deploy
      script:
        - cd prisma && prisma generate && prisma deploy && cd ..
        - npm run build
        - docker login --username $DOCKER_USER -p $DOCKER_PASS
        - docker build -t rctechclub/phoenix:dev .
        - docker push rctechclub/phoenix:dev
