version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - phoenix:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  phoenix:
