version: 2

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10
    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  test:
    docker:
      # specify the version you desire here
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      # run tests!
      - run: npm run test

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build