version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: 4466
        databases:
          default:
            connector: postgres
            host: ${DB_HOST}
            user: ${DB_USER}
            password: ${DB_PASSWORD}
            port: 5432
            migrations: true
