name: Run tests for Phoenix

on:
  push:
    branches-ignore:
      - master
  pull_request:

env:
  PRISMA_HOST: http://localhost:4466/prisma
  PRISMA_MANAGEMENT_API_SECRET: secret123
  PRISMA_SECRET: secret123
  DB_HOST: postgres
  DB_USER: prisma
  DB_PASSWORD: prisma
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  NODEMAILER_PASSWORD: ${{ secrets.NODEMAILER_PASSWORD }}
  SLS_SECRET: ${{ secrets.SLS_SECRET }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use NodeJS stable
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install
        run: |
          docker-compose -f prisma/docker-compose.yml up -d
          npm install -g prisma
          npm install
          cd prisma && prisma generate && prisma deploy

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: rctechclub/phoenix:dev
