name: Deploy Phoenix

on:
  push:
    branches:
      - master

env:
  PHOENIX_SECRET: ${{ secrets.PHOENIX_SECRET }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  NODEMAILER_PASSWORD: ${{ secrets.NODEMAILER_PASSWORD }}
  SLS_SECRET: ${{ secrets.SLS_SECRET }}

jobs:
  dockerimage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Use NodeJS stable
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push prod to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rctechclub/phoenix:prod

      - name: Push latest to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rctechclub/phoenix:latest

  heroku:
    needs: dockerimage
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "rctech-phoenix" #Must be unique in Heroku
          heroku_email: "technology@rctech.club"
          dontautocreate: true
          healthcheck: "https://phoenix.rctech.club"
