name: Deploy Phoenix

on:
  push:
    branches:
      - master

env:
  PRISMA_HOST: ${{ secrets.PRISMA_HOST }}
  PRISMA_MANAGEMENT_API_SECRET: ${{ secrets.PRISMA_MANAGEMENT_API_SECRET }}
  PRISMA_SECRET: ${{ secrets.PRISMA_SECRET }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  NODEMAILER_PASSWORD: ${{ secrets.NODEMAILER_PASSWORD }}
  SLS_SECRET: ${{ secrets.SLS_SECRET }}

jobs:
  dockerimage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        run: |
          npm install -g prisma
          npm install
          cd prisma && prisma generate && prisma deploy
          npm run build

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: rctechclub/phoenix:latest
