name: Deploy Phoenix

on: [push]
# on:
# push:
#   branches:
#     - master

env:
  PRISMA_HOST: ${{ secrets.PRISMA_HOST }}
  PRISMA_MANAGEMENT_API_SECRET: ${{ secrets.PRISMA_MANAGEMENT_API_SECRET }}
  PRISMA_SECRET: ${{ secrets.PRISMA_SECRET }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  NODEMAILER_PASSWORD: ${{ secrets.NODEMAILER_PASSWORD }}
  SLS_SECRET: ${{ secrets.SLS_SECRET }}

jobs:
  dockerimage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Use NodeJS stable
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Build
        run: |
          npm install -g prisma
          npm install
          cd prisma && prisma generate && prisma deploy
          npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push prod to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: rctechclub/phoenix:prod

      - name: Push latest to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: rctechclub/phoenix:latest

  aws:
    needs: dockerimage
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Update phoenix ECS service
        run: |
          aws ecs update-service --cluster phoenix --service phoenix --force-new-deployment --region us-east-2
